### ISSUE TITLE
补充最近看到的一些

### ISSUE THREAD

**Issue by samzong** [lvwzhen/sh-help#1]
- 上海-各类物资采购渠道 https://docs.qq.com/sheet/DSnBQbFFidmNQTFlQ?tab=BB08J2&scode=
- 查询小区感染记录 https://chenfan.info/
- 魔都防疫指南3.3[更新及时] https://shimo.im/docs/0l3NV5lEwOfpQx3R/read

**Comment by samzong** [comment]
- 上海疫情期间线上活动汇总 https://docs.qq.com/sheet/DR3p2dmF4Znh6Rlp0?tab=BB08J2&scode=

**Comment by samzong** [comment]
- 上海疫情守望互助指南 (by 海上指南针) https://shimo.im/docs/loqeWyQor8SLYYAn/read

**Comment by lvwzhen** [comment]
谢谢反馈

**Comment by samzong** [comment]
- 上海封城期间的一些事情repo, issue很值得看 https://github.com/R-r-riddikulus/riddikulus-shanghai-2022/issues

**Comment by wangshengfa** [comment]
操盘手1：筹码分布操盘实战.pdf: https://url47.ctfile.com/f/178047-560577342-8c1998 （访问密码：8862）
操盘手2：量价分析操盘实战.pdf: https://url47.ctfile.com/f/178047-560577367-7db781 （访问密码：8862）
操盘手3：散户斗庄的16个细节.pdf: https://url47.ctfile.com/f/178047-560577390-c97e1c （访问密码：8862）
操盘手4：用均线抓到大行情.pdf: https://url47.ctfile.com/f/178047-560577403-575581 （访问密码：8862）
批判性思维-(美)理查德.保罗.pdf: https://url47.ctfile.com/f/178047-560577329-1a4eb0 （访问密码：8862）
日本蜡烛图技术.pdf: https://url47.ctfile.com/f/178047-560577416-53f9ae （访问密码：8862）
十年一梦-一个操盘手的自白.pdf: https://url47.ctfile.com/f/178047-560577432-24f1b2 （访问密码：8862）
投机的魅力.pdf: https://url47.ctfile.com/f/178047-560577439-bebbd7 （访问密码：8862）
投资中最简单的事（完整版）.pdf: https://url47.ctfile.com/f/178047-560577467-6322ae （访问密码：8862）
中国股市操练大全：超值白金版.pdf: https://url47.ctfile.com/f/178047-560577483-5ecdb1 （访问密码：8862）
